### ISSUE TITLE
Generalize toolbar widget structure

### ISSUE THREAD

**Issue by jsoules** [flatironinstitute/labbox-ephys#310]
We don't have a whole lot of these just yet, but items such as [TimeWidgetToolbarNew.tsx](https://github.com/laboratorybox/labbox-ephys/blob/c3633cce161783e13314bdf971e6ca83c19424a6/src/extensions/timeseries/TimeWidgetNew/TimeWidgetToolbarNew.tsx) will soon be joined by other toolbars following a similar structure. The structure already approximates a flexible separation of display and function (with the `customActions` property).

I think it'd be worthwhile to expand that into a toolbar widget framework that handles toolbars generally. Then individual panel views can display a toolbar by passing an array of objects defined in data (as per the custom actions), with an optional 'divider' action type for visual dividers.

Low priority right now.

**Comment by magland** [comment]
I completely agree, and would in fact bump this up to higher priority.

In addition to adding actions, we should make it easy to add electrode selection or unit selection views.
