### ISSUE TITLE
Stress test/investigate performance degradation in python API with large feed-based data sets

### ISSUE THREAD

**Issue by jsoules** [flatironinstitute/labbox-ephys#332]
Before public release/solicitation of outside users, we should do some stress-testing with the large (several-gigabyte) datasets from the Neuropixels conference.

I can anecdotally report the python API process consuming CPU to the point of causing system instability when a Chrome tab with the feed http://localhost:15351/default/sorting/cortexlab-drift-dataset1:spyking_circus?feed=sha1://964933faf311bbc69efbf0b8c1b541e77f5a3073/feed.json was populated for ~30-45 minutes (with minimal interaction).

I have not attempted to reproduce this issue, but it will be important in the future to make a systematic effort to do so.

**Comment by magland** [comment]
We'll do this once we have a large workspace of all of the spikeforest recordings.
