### ISSUE TITLE
Going from NwbR/SExtractor to LabboxEphysR/SE

### ISSUE THREAD

**Issue by khl02007** [flatironinstitute/labbox-ephys#357]
Right now what we do is:
1. start with an NWB file
2. create a NwbRecordingExtractor from the NWB file
3. create a SubRecordingExtractor of the NwbRecordingExtractor from step 2 (for the chunk of the recording we want to sort)
4. save this SubRecordingExtractor as a NWB file using [se.NwbRecordingExtractor.write_recording](https://github.com/SpikeInterface/spikeextractors/blob/7a7f6faa6ad6c4dcfb593bab8b11fb988de1a9c5/spikeextractors/extractors/nwbextractors/nwbextractors.py#L857) method (note: this seems [buggy](https://github.com/SpikeInterface/spikeextractors/issues/546))
5. sort the SubRecordingExtractor and generate a SortingExtractor
6. save this SortingExtractor to the same NWB file as in step 4
7. use `from_memory` method of LabboxEphysRecording and SortingExtractors to generate LE R/S
8. launch MV sorting view from results of step 7
9. curate and find units to merge
10. update the SortingExtractor from step 5 based on the merges
11. repeat steps 6-9

There is probably room for improvement, esp if we end up using feeds.
If possible we would like code snippets that would make this easier, specifically
- generating LE R/S
- updating Sorting based on merges

**Comment by magland** [comment]
@khl02007, working on this now. Could you please send me an example recording and sorting .nwb so I can test on this end?

You could use dropbox, but if you want to try the kachery-p2p method you would just do:

```
import kachery as ka
recording_uri = ka.store_file('/path/to/file.nwb')
print(recording_uri)
```

and then send me the URI

(similar for sorting)

**Comment by magland** [comment]
This will be implemented once the following PR is merged: https://github.com/laboratorybox/labbox-ephys/pull/367
