### ISSUE TITLE
Extend from_spikeinterface function

### ISSUE THREAD

**Issue by alejoe91** [flatironinstitute/labbox-ephys#417]
Hi @magland 

Right now the `from_spikeinterface` function only supports a few SI classes. Could we extend it in some way to support all SI objects? 

Also, can we add a `from_spikeinterface` to the `LabboxEphysSortingExtractor` as well?

We cna have a chat to discuss about that :)

Cheers
Alessio

**Comment by magland** [comment]
Sounds good. Could we enumerate the cases that we need to cover? Maybe in a gh issue checklist, and that way we can track the progress? What's the easiest way to make that list?

**Comment by alejoe91** [comment]
Hi @magland

I think it would be an unnecessary amount of work to copy all possible cases in SI to an enumeration. Plus, the information is already there in the `dump_to_dict`. I think that the best option would be to extend the [function](https://github.com/flatironinstitute/labbox-ephys/blob/main/python/labbox_ephys/extractors/_spikeinterface_recording_dict_to_labbox_dict.py#L33) to systematically handle all possibilities. 

I understand your concern about class names, BUT we also save the version of the package, so it should be fine in my opinion.
