### ISSUE TITLE
Spike sorting

### ISSUE THREAD

**Issue by magland** [flatironinstitute/labbox-ephys#419]
Allow user to perform spike sorting. In recording view, user clicks "spike sorting" button. They are then given a script for running spike sorting for that recording. At the end of the script, the new sorting object is inserted into the workspace.

**Comment by magland** [comment]
@wufan0504: this may be of interest to you - might be ready to test in the next couple of days.

**Comment by wufan0504** [comment]
Thank you, will look into it right away!

**Comment by magland** [comment]
See: https://github.com/flatironinstitute/labbox-ephys/pull/444
