### ISSUE TITLE
Adding external metrics to workspace

### ISSUE THREAD

**Issue by khl02007** [flatironinstitute/labbox-ephys#436]
Right now external metrics are added by first initializing `sorting_views.MVSortingView` and then using `set_external_unit_metrics` method. If we use workspaces then we wouldn't do the first step. Can we do `workspace.add_external_metrics`?

**Comment by magland** [comment]
Yes, that's a good idea. Maybe...

```
# prepare a pandas dataframe
workspace.set_external_unit_metrics(sorting_id, dataframe)
```

Note I propose to use 'set' instead of 'add'. The dataframe will be serialized and stored in kachery, and the workspace will have the URI pointer.
