### ISSUE TITLE
Ensure consistent order for cross-correlograms

### ISSUE THREAD

**Issue by jsoules** [flatironinstitute/labbox-ephys#441]
Currently, cross-correlograms in the cross-correlogram widget are laid out in the order in which the units were clicked. This can lead to somewhat confusing display when multiple cross-correlogram views with the same set of selected units are displayed:

![image](https://user-images.githubusercontent.com/2347301/107659789-8a1b5880-6c55-11eb-87ba-c955ed4982d6.png)

As the screenshot shows, both windows have units 2, 4, and 7 selected, but the top one has 2's autocorrelogram in the upper left, while the bottom one has 7's autocorrelogram; the other unit pairings similarly don't correspond.

To fix, perhaps sort the selected units in the cross-correlogram local unit selection list during update?

**Comment by magland** [comment]
transferred to: https://github.com/magland/sortingview/issues/45
