### ISSUE TITLE
Curation completed button

### ISSUE THREAD

**Issue by lfrank** [flatironinstitute/labbox-ephys#463]
It would be helpful if the user could click a "curation completed" or just "Completed" button which would add a tag to that effect. That would allow us to look for that tag in the workspace and only add to the CuratedSpikeSorting table when the curation was ready.

A related issue is that the widget continues to run forever, and it would be useful to be able to stop it so it isn't using system resources. Perhaps a "done" button?

**Comment by magland** [comment]
transferred to: https://github.com/magland/sortingview/issues/41
