### ISSUE TITLE
Computing metrics using labbox recording extractors

### ISSUE THREAD

**Issue by lfrank** [flatironinstitute/labbox-ephys#464]
Currently this seems to hang, following lots of messages like

Chunk 52: extracting waveforms
Exception ignored in: <function BaseExtractor.__del__ at 0x7f4be5b7ec10>
Traceback (most recent call last):
  File "/home/loren/Src/NWB/spikeextractors/spikeextractors/baseextractor.py", line 36, in __del__
    for memmap_obj in self._memmap_files:
AttributeError: 'LabboxEphysRecordingExtractor' object has no attribute '_memmap_files'

But it's not clear why it hangs.

**Comment by magland** [comment]
Please provide self-contained example (ideally .py script) to reproduce.

**Comment by magland** [comment]
i think it's resolved in sortingview.
