### ISSUE TITLE
Feature request: high efficiency recording / sorting extractor

### ISSUE THREAD

**Issue by lfrank** [flatironinstitute/labbox-ephys#470]
Given the time it takes to write NWB recording extractors, we would greatly benefit from a new, high efficiency recording extractor that could also hold the sorting data and still allow us to be fully compatible with spikeInterface, ideally without running 
recording = st.CacheRecordingExtractor(recording) first.

For reference:
Elapsed time for writing filtered NWB recording extractor to /stelmo/nwb/spikesorting/despereaux20191125_000003.nwb/despereaux20191125_.nwb_02_r1_11_mountainsort4_franklab_tetrode_hippocampus_30KHz.nwb: **1325.946664571762 sec**

**Comment by magland** [comment]
I believe this has been addressed. Please reopen in sortingview if not.
