### ISSUE TITLE
blank curating window when using high efficiency recording extractor

### ISSUE THREAD

**Issue by lfrank** [flatironinstitute/labbox-ephys#475]
When using the high efficiency extractor, the curating window looks fine for ~.5 seconds and shows the recording and then goes blank. This doesn't happen with the NwbRecordingExtractor.

Here's the code I'm using to create / insert it:
`And as a follow up, this doesn’t happen when I switch back to the NWB sorting / recording extractor; then things look fine. If it helps, here is the code I’m using to create the labbox extractor:

         le.extractors.H5RecordingExtractorV1.write_recording(recording, recording_extractor_h5_path)
        # whiten the extractor for sorting and metric calculations
        print('\nWhitening recording...')
        with Timer(label=f'whiteneing', verbose=True):
            filter_params = (SpikeSorterParameters & {'sorter_name': key['sorter_name'],
                                                    'parameter_set_name': key['parameter_set_name']}).fetch1('filter_parameter_dict')
            recording = st.preprocessing.whiten(recording, seed=0, chunk_size=filter_params['filter_chunk_size'])

        print(f'\nRunning spike sorting on {key}...')
        sort_parameters = (SpikeSorterParameters & {'sorter_name': key['sorter_name'],
                                                    'parameter_set_name': key['parameter_set_name']}).fetch1()
        
        sorting = ss.run_sorter(key['sorter_name'], recording,
                                output_folder=os.getenv('SORTING_TEMP_DIR', None),
                                **sort_parameters['parameter_dict'])

        with Timer(label='computing quality metrics', verbose=True):
            metrics_key = (SpikeSortingParameters & key).fetch1('cluster_metrics_list_name')    
            metric_info = (SpikeSortingMetrics & {'cluster_metrics_list_name': metrics_key }).fetch1()
            print(metric_info) 
            metrics = SpikeSortingMetrics().compute_metrics(metrics_key, recording, sorting)

        print('\nSaving sorting results...')
        units = dict()
        units_valid_times = dict()
        units_sort_interval = dict()
        unit_ids = sorting.get_unit_ids()
        for unit_id in unit_ids:
            spike_times_in_samples = sorting.get_unit_spike_train(unit_id = unit_id)
            units[unit_id] = recording_timestamps[spike_times_in_samples]
            units_valid_times[unit_id] = sort_interval_valid_times
            units_sort_interval[unit_id] = [sort_interval]

        print('\nGenerating feed for curation...')
        recording_extractor_h5_uri = kp.link_file(recording_extractor_h5_path)
        
        # create workspace
        workspace_uri = kp.get(key['analysis_file_name'])
        if not workspace_uri:
            workspace_uri = le.create_workspace(label=key['analysis_file_name']).uri
            kp.set(key['analysis_file_name'], workspace_uri)
        workspace = le.load_workspace(workspace_uri)
        print(f'Workspace URI: {workspace.uri}')
        
        recording_label = key['nwb_file_name']+'_'+key['sort_interval_name']+'_'+str(key['sort_group_id'])
        sorting_label = key['sorter_name']+'_'+key['parameter_set_name']

        recording_uri = kp.store_json({
            'recording_format': 'h5_v1',
            'data': {
                'h5_uri': recording_extractor_h5_uri,
            }
        })

        le_sorting = le.LabboxEphysSortingExtractor.store_sorting(sorting)
        labbox_sorting = le.LabboxEphysSortingExtractor(le_sorting)
        labbox_recording = le.LabboxEphysRecordingExtractor(recording_uri, download=True)

        R_id = workspace.add_recording(recording=labbox_recording, label=recording_label)
        S_id = workspace.add_sorting(sorting=labbox_sorting, recording_id=R_id, label=sorting_label)               
        
        key['curation_feed_uri'] = workspace.uri

        # Set external metrics that will appear in the units table
        external_metrics = [{'name': metric, 'label': metric, 'tooltip': metric,
                             'data': metrics[metric].to_dict()} for metric in metrics.columns]
        # change unit id to string
        for metric_ind in range(len(external_metrics)):
            for old_unit_id in metrics.index:
                external_metrics[metric_ind]['data'][str(old_unit_id)] = external_metrics[metric_ind]['data'].pop(old_unit_id)
        workspace.set_unit_metrics_for_sorting(sorting_id=S_id, metrics=external_metrics)
        
        # add to the web app as well
        workspace_list = sortingview.WorkspaceList(backend_uri='gs://labbox-franklab/sortingview-backends/franklab.json')
        workspace_list.add_workspace(name=key['analysis_file_name'], workspace=workspace)`

**Comment by magland** [comment]
Closing this for now because it may not be an issue any more, but feel free to reopen if still relevant.
