### ISSUE TITLE
Problems with API and socket

### ISSUE THREAD

**Issue by LastingDynamics2** [flatironinstitute/labbox-ephys#73]
We are attempting to build a testing environment where we could perform QA, but we have some troubles with API and sockets, the UI loads forever and network tab doesn't return any error so we might have some configuration issue.
In particular I'd like to know
1 - if there is any remote API that frontend can connect to
2 - how to change the url of API and websocket and any other BE serivce from localhost to the custom url

thank you for the help

**Comment by magland** [comment]
Happy to help. Those things are configurable, and it is possible to set up a remote API. First, are you able to get the system working within the containerized vscode environment (devcontainer)?

**Comment by LastingDynamics2** [comment]
yes.it work.The only issue we have is that when we try to import an report using examples is start loading but is stays on loading state and nothing happen on the network tab

**Comment by magland** [comment]
Okay, I guess that's something we need to troubleshoot. Please send an email and we can set up a zoom call to figure out why the example data is not being downloaded properly.

**Comment by magland** [comment]
Make a button on the GUI that says 'disconnected, click to reconnect'
